theme: minima

minima:
 social_links:
 - { platform: discord,          user_url: "https://discord.gg/mCxu9CXbhT" }

plugins:
  - jekyll-feed

header_pages:
  - README.md
  - criterion_dungeon/README.md
  - criterion_dungeon/AMR/README.md